apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake
  template:
    metadata:
      labels:
        app: fake
    spec:
      containers:
      - name: api
        image: fake/fake:0.0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: fake-service
  labels:
    app: fake-service
spec:
  ports:
  - port: 5000
    name: http
    targetPort: 5000
  selector:
    app: fake