apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fake
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
        - path: /register
          pathType: ImplementationSpecific
          backend:
            service:
              name: fake-service
              port:
                number: 5000
        - path: /key
          pathType: ImplementationSpecific
          backend:
            service:
              name: fake-service
              port:
                number: 5000